### ISSUE TITLE
ACLLib 的一点使用问题

### ISSUE THREAD

**Issue by CodeChikoto** [wengkai/ACLLib#4]
在一个函数内：
beginPaint();
.....
endPaint();
initConsole();
.....
beginPaint();
.....
endPaint();
为什么第一处 Paint 的内容不会显示，等到 Console 执行完后，直接显示第二处 Paint 的内容？

**Comment by Mochimazui** [comment]
beginPaint 和 endPaint 之间的绘制函数并不是直接绘制到屏幕上，而是先绘制到后台一张位图里。等控制权回到 ACLLib （用户的 Setup 函数、鼠标或键盘等回调函数执行结束）后才会更新到屏幕上。
